// Made by build-index.js. Don't edit this by hand, run "node build-index.js" instead.
const docsIndex = [
    {"page":"index.html","kind":"page","id":"","title":"What is MDog Engine?"},
    {"page":"index.html","kind":"heading","id":"made-with-mdog-engine","title":"Made with MDog Engine","context":"What is MDog Engine?"},
    {"page":"index.html","kind":"heading","id":"modules","title":"Modules","context":"What is MDog Engine?"},
    {"page":"index.html","kind":"heading","id":"how-it-works","title":"How it Works","context":"What is MDog Engine?"},
    {"page":"getting-started.html","kind":"page","id":"","title":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"1-make-the-project","title":"1. Make the Project","context":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"2-make-the-web-page","title":"2. Make the Web Page","context":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"3-write-the-game","title":"3. Write the Game","context":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"4-run-the-game","title":"4. Run the Game","context":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"5-add-an-image","title":"5. Add an Image","context":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"fonts","title":"6. Add Text","context":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"7-share-it","title":"7. Share It","context":"Getting Started"},
    {"page":"getting-started.html","kind":"heading","id":"tips","title":"Tips","context":"Getting Started"},
    {"page":"core.html","kind":"page","id":"","title":"Core"},
    {"page":"core.html","kind":"heading","id":"the-game-loop","title":"The Game Loop","context":"Core"},
    {"page":"core.html","kind":"heading","id":"core-methods","title":"Core Methods","context":"Core"},
    {"page":"core.html","kind":"heading","id":"properties","title":"Properties","context":"Core"},
    {"page":"core.html","kind":"heading","id":"modules","title":"Modules","context":"Core"},
    {"page":"core.html","kind":"method","id":"setActiveFunction","title":"setActiveFunction()","name":"setActiveFunction","owner":null,"constructs":null,"description":"Sets the function that runs every tick.","context":"Core"},
    {"page":"draw.html","kind":"page","id":"","title":"Draw Module"},
    {"page":"draw.html","kind":"heading","id":"drawing-methods","title":"Drawing Methods","context":"Draw Module"},
    {"page":"draw.html","kind":"heading","id":"setup-methods","title":"Setup Methods","context":"Draw Module"},
    {"page":"draw.html","kind":"heading","id":"info-methods","title":"Info Methods","context":"Draw Module"},
    {"page":"draw.html","kind":"heading","id":"animations","title":"Animations","context":"Draw Module"},
    {"page":"draw.html","kind":"heading","id":"constructors","title":"Constructors","context":"Draw Module"},
    {"page":"draw.html","kind":"heading","id":"animation-methods","title":"Animation Methods","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"animation","title":"animation()","name":"animation","owner":null,"constructs":null,"description":"Draws an animation.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"circle","title":"circle()","name":"circle","owner":null,"constructs":null,"description":"Draws a circle.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"clear","title":"clear()","name":"clear","owner":null,"constructs":null,"description":"Clears the screen/layer to a color.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"image","title":"image()","name":"image","owner":null,"constructs":null,"description":"Draws an image.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"interactable","title":"interactable()","name":"interactable","owner":null,"constructs":null,"description":"Draws an interactable.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"line","title":"line()","name":"line","owner":null,"constructs":null,"description":"Draws a line.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"particleSystem","title":"particleSystem()","name":"particleSystem","owner":null,"constructs":null,"description":"Draws a particle system.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"point","title":"point()","name":"point","owner":null,"constructs":null,"description":"Sets a pixel.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"polygon","title":"polygon()","name":"polygon","owner":null,"constructs":null,"description":"Draws the outline of a polygon.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"polygonFill","title":"polygonFill()","name":"polygonFill","owner":null,"constructs":null,"description":"Draws a filled polygon.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"rectangle","title":"rectangle()","name":"rectangle","owner":null,"constructs":null,"description":"Draws the outline of a rectangle.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"rectangleFill","title":"rectangleFill()","name":"rectangleFill","owner":null,"constructs":null,"description":"Draws a filled-in rectangle.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"textImage","title":"textImage()","name":"textImage","owner":null,"constructs":null,"description":"Draws pixel font text.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"threeDeeScene","title":"threeDeeScene()","name":"threeDeeScene","owner":null,"constructs":null,"description":"Draws a threeDeeScene.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"translate","title":"translate()","name":"translate","owner":null,"constructs":null,"description":"Shifts the screen.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"translateX","title":"translateX()","name":"translateX","owner":null,"constructs":null,"description":"Shifts the screen horizontally.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"translateY","title":"translateY()","name":"translateY","owner":null,"constructs":null,"description":"Shifts the screen vertically.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"preloadAnimation","title":"preloadAnimation()","name":"preloadAnimation","owner":null,"constructs":null,"description":"Starts loading an animation.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"setActiveLayer","title":"setActiveLayer()","name":"setActiveLayer","owner":null,"constructs":null,"description":"Sets the default draw layer.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"setBackgroundColor","title":"setBackgroundColor()","name":"setBackgroundColor","owner":null,"constructs":null,"description":"Sets the color of the dom body.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"setScreenSize","title":"setScreenSize()","name":"setScreenSize","owner":null,"constructs":null,"description":"Sets the size of the screen.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"findIntersections","title":"findIntersections()","name":"findIntersections","owner":null,"constructs":null,"description":"Finds where a row crosses a polygon.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"getScreenHeightInArtPixels","title":"getScreenHeightInArtPixels()","name":"getScreenHeightInArtPixels","owner":null,"constructs":null,"description":"Gets the height of the screen.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"getScreenWidthInArtPixels","title":"getScreenWidthInArtPixels()","name":"getScreenWidthInArtPixels","owner":null,"constructs":null,"description":"Gets the width of the screen.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"getHalfScreenHeightInArtPixels","title":"getHalfScreenHeightInArtPixels()","name":"getHalfScreenHeightInArtPixels","owner":null,"constructs":null,"description":"Gets the int height of half of the screen.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"getHalfScreenWidthInArtPixels","title":"getHalfScreenWidthInArtPixels()","name":"getHalfScreenWidthInArtPixels","owner":null,"constructs":null,"description":"Gets the int width of half of the screen.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"measureText","title":"measureText()","name":"measureText","owner":null,"constructs":null,"description":"Gets the length of theoretical text.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"new-MultipleFileAnimation","title":"new MultipleFileAnimation()","name":"new MultipleFileAnimation","owner":null,"constructs":"MultipleFileAnimation","description":"Makes an animation from many images.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"new-SpriteSheetAnimation","title":"new SpriteSheetAnimation()","name":"new SpriteSheetAnimation","owner":null,"constructs":"SpriteSheetAnimation","description":"Makes an animation from a sprite sheet.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"Animation.getFrame","title":"Animation.getFrame()","name":"getFrame","owner":"Animation","constructs":null,"description":"Gets the current frame.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"Animation.getRawFrame","title":"Animation.getRawFrame()","name":"getRawFrame","owner":"Animation","constructs":null,"description":"Gets how many frames have passed.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"Animation.reset","title":"Animation.reset()","name":"reset","owner":"Animation","constructs":null,"description":"Restarts the animation.","context":"Draw Module"},
    {"page":"draw.html","kind":"method","id":"Animation.getImage","title":"Animation.getImage()","name":"getImage","owner":"Animation","constructs":null,"description":"Gets a frame's file name.","context":"Draw Module"},
    {"page":"input.html","kind":"page","id":"","title":"Input Module"},
    {"page":"input.html","kind":"heading","id":"keyboard","title":"Keyboard","context":"Input Module"},
    {"page":"input.html","kind":"heading","id":"mouse","title":"Mouse","context":"Input Module"},
    {"page":"input.html","kind":"heading","id":"mouse-info-methods","title":"Mouse Info Methods","context":"Input Module"},
    {"page":"input.html","kind":"heading","id":"mouse-cursor-methods","title":"Mouse Cursor Methods","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Keyboard.isDown","title":"Keyboard.isDown()","name":"isDown","owner":"Keyboard","constructs":null,"description":"Checks if a key is held.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Keyboard.isClicked","title":"Keyboard.isClicked()","name":"isClicked","owner":"Keyboard","constructs":null,"description":"Checks if a key was just pressed.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.getClick","title":"Mouse.getClick()","name":"getClick","owner":"Mouse","constructs":null,"description":"Checks if a button was just pressed.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.getDown","title":"Mouse.getDown()","name":"getDown","owner":"Mouse","constructs":null,"description":"Checks if a button is held.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.getOnScreen","title":"Mouse.getOnScreen()","name":"getOnScreen","owner":"Mouse","constructs":null,"description":"Checks if the mouse is over the game.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.getX","title":"Mouse.getX()","name":"getX","owner":"Mouse","constructs":null,"description":"Gets the x position of the mouse.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.getY","title":"Mouse.getY()","name":"getY","owner":"Mouse","constructs":null,"description":"Gets the y position of the mouse.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.requestStyle","title":"Mouse.requestStyle()","name":"requestStyle","owner":"Mouse","constructs":null,"description":"Sets the cursor style.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.getNewStyle","title":"Mouse.getNewStyle()","name":"getNewStyle","owner":"Mouse","constructs":null,"description":"Gets the requested cursor style.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.style","title":"Mouse.style()","name":"style","owner":"Mouse","constructs":null,"description":"Applies the requested cursor style.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.show","title":"Mouse.show()","name":"show","owner":"Mouse","constructs":null,"description":"Shows the cursor.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.hide","title":"Mouse.hide()","name":"hide","owner":"Mouse","constructs":null,"description":"Hides the cursor.","context":"Input Module"},
    {"page":"input.html","kind":"method","id":"Mouse.disableContextMenu","title":"Mouse.disableContextMenu()","name":"disableContextMenu","owner":"Mouse","constructs":null,"description":"Turns off the right click menu.","context":"Input Module"},
    {"page":"math.html","kind":"page","id":"","title":"Math Module"},
    {"page":"math.html","kind":"heading","id":"math-methods","title":"Math Methods","context":"Math Module"},
    {"page":"math.html","kind":"heading","id":"vector","title":"Vector","context":"Math Module"},
    {"page":"math.html","kind":"heading","id":"constructor","title":"Constructor","context":"Math Module"},
    {"page":"math.html","kind":"heading","id":"vector-methods","title":"Vector Methods","context":"Math Module"},
    {"page":"math.html","kind":"heading","id":"vector3","title":"Vector3","context":"Math Module"},
    {"page":"math.html","kind":"heading","id":"constructor-2","title":"Constructor","context":"Math Module"},
    {"page":"math.html","kind":"heading","id":"vector3-methods","title":"Vector3 Methods","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"deltaTime","title":"deltaTime()","name":"deltaTime","owner":null,"constructs":null,"description":"Gets the time since the last frame.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"lerp","title":"lerp()","name":"lerp","owner":null,"constructs":null,"description":"Blends between two numbers.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"new-Vector","title":"new Vector()","name":"new Vector","owner":null,"constructs":"Vector","description":"Makes a new vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.add","title":"Vector.add()","name":"add","owner":"Vector","constructs":null,"description":"Adds to this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.clone","title":"Vector.clone()","name":"clone","owner":"Vector","constructs":null,"description":"Copies this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.constrain","title":"Vector.constrain()","name":"constrain","owner":"Vector","constructs":null,"description":"Limits the length of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.distanceTo","title":"Vector.distanceTo()","name":"distanceTo","owner":"Vector","constructs":null,"description":"Gets the distance to another vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.divide","title":"Vector.divide()","name":"divide","owner":"Vector","constructs":null,"description":"Divides this vector by a number.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.dotProduct","title":"Vector.dotProduct()","name":"dotProduct","owner":"Vector","constructs":null,"description":"Gets the dot product.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.equals","title":"Vector.equals()","name":"equals","owner":"Vector","constructs":null,"description":"Checks if two vectors are the same.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.getAngle","title":"Vector.getAngle()","name":"getAngle","owner":"Vector","constructs":null,"description":"Gets the angle of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.getX","title":"Vector.getX()","name":"getX","owner":"Vector","constructs":null,"description":"Gets the x of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.getY","title":"Vector.getY()","name":"getY","owner":"Vector","constructs":null,"description":"Gets the y of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.length","title":"Vector.length()","name":"length","owner":"Vector","constructs":null,"description":"Gets the length of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.multiply","title":"Vector.multiply()","name":"multiply","owner":"Vector","constructs":null,"description":"Multiplies this vector by a number.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.normalize","title":"Vector.normalize()","name":"normalize","owner":"Vector","constructs":null,"description":"Sets the length of this vector to 1.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.rotate","title":"Vector.rotate()","name":"rotate","owner":"Vector","constructs":null,"description":"Rotates this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.set","title":"Vector.set()","name":"set","owner":"Vector","constructs":null,"description":"Sets this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.setLength","title":"Vector.setLength()","name":"setLength","owner":"Vector","constructs":null,"description":"Sets the length of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.setX","title":"Vector.setX()","name":"setX","owner":"Vector","constructs":null,"description":"Sets the x of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.setY","title":"Vector.setY()","name":"setY","owner":"Vector","constructs":null,"description":"Sets the y of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.subtract","title":"Vector.subtract()","name":"subtract","owner":"Vector","constructs":null,"description":"Subtracts from this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector.toString","title":"Vector.toString()","name":"toString","owner":"Vector","constructs":null,"description":"Gets this vector as text.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"new-Vector3","title":"new Vector3()","name":"new Vector3","owner":null,"constructs":"Vector3","description":"Makes a new 3D vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.add","title":"Vector3.add()","name":"add","owner":"Vector3","constructs":null,"description":"Adds to this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.clone","title":"Vector3.clone()","name":"clone","owner":"Vector3","constructs":null,"description":"Copies this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.constrain","title":"Vector3.constrain()","name":"constrain","owner":"Vector3","constructs":null,"description":"Limits the length of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.distanceTo","title":"Vector3.distanceTo()","name":"distanceTo","owner":"Vector3","constructs":null,"description":"Gets the distance to another vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.getX","title":"Vector3.getX()","name":"getX","owner":"Vector3","constructs":null,"description":"Gets the x of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.getY","title":"Vector3.getY()","name":"getY","owner":"Vector3","constructs":null,"description":"Gets the y of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.getZ","title":"Vector3.getZ()","name":"getZ","owner":"Vector3","constructs":null,"description":"Gets the z of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.length","title":"Vector3.length()","name":"length","owner":"Vector3","constructs":null,"description":"Gets the length of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.multiply","title":"Vector3.multiply()","name":"multiply","owner":"Vector3","constructs":null,"description":"Multiplies this vector by a number.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.normalize","title":"Vector3.normalize()","name":"normalize","owner":"Vector3","constructs":null,"description":"Sets the length of this vector to 1.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.set","title":"Vector3.set()","name":"set","owner":"Vector3","constructs":null,"description":"Sets this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.setLength","title":"Vector3.setLength()","name":"setLength","owner":"Vector3","constructs":null,"description":"Sets the length of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.setX","title":"Vector3.setX()","name":"setX","owner":"Vector3","constructs":null,"description":"Sets the x of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.setY","title":"Vector3.setY()","name":"setY","owner":"Vector3","constructs":null,"description":"Sets the y of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.setZ","title":"Vector3.setZ()","name":"setZ","owner":"Vector3","constructs":null,"description":"Sets the z of this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.subtract","title":"Vector3.subtract()","name":"subtract","owner":"Vector3","constructs":null,"description":"Subtracts from this vector.","context":"Math Module"},
    {"page":"math.html","kind":"method","id":"Vector3.toString","title":"Vector3.toString()","name":"toString","owner":"Vector3","constructs":null,"description":"Gets this vector as text.","context":"Math Module"},
    {"page":"ui.html","kind":"page","id":"","title":"UI Module"},
    {"page":"ui.html","kind":"heading","id":"page","title":"Page","context":"UI Module"},
    {"page":"ui.html","kind":"heading","id":"interactable","title":"Interactable","context":"UI Module"},
    {"page":"ui.html","kind":"heading","id":"textinteractable","title":"TextInteractable","context":"UI Module"},
    {"page":"ui.html","kind":"heading","id":"tilemapinteractable","title":"TilemapInteractable","context":"UI Module"},
    {"page":"ui.html","kind":"heading","id":"rectanglegridinteractable","title":"RectangleGridInteractable","context":"UI Module"},
    {"page":"ui.html","kind":"heading","id":"vectorgridinteractable","title":"VectorGridInteractable","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"new-Page","title":"new Page()","name":"new Page","owner":"Page","constructs":"Page","description":"Makes a new page.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Page.addInteractable","title":"Page.addInteractable()","name":"addInteractable","owner":"Page","constructs":null,"description":"Adds an interactable to the page.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Page.update","title":"Page.update()","name":"update","owner":"Page","constructs":null,"description":"Updates every interactable.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Page.draw","title":"Page.draw()","name":"draw","owner":"Page","constructs":null,"description":"Draws every interactable.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"new-Interactable","title":"new Interactable()","name":"new Interactable","owner":"Interactable","constructs":"Interactable","description":"Makes a new interactable.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Interactable.getMouseOver","title":"Interactable.getMouseOver()","name":"getMouseOver","owner":"Interactable","constructs":null,"description":"Checks if the mouse is over it.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Interactable.getX","title":"Interactable.getX()","name":"getX","owner":"Interactable","constructs":null,"description":"Gets the x position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Interactable.getY","title":"Interactable.getY()","name":"getY","owner":"Interactable","constructs":null,"description":"Gets the y position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Interactable.setX","title":"Interactable.setX()","name":"setX","owner":"Interactable","constructs":null,"description":"Sets the x position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"Interactable.setY","title":"Interactable.setY()","name":"setY","owner":"Interactable","constructs":null,"description":"Sets the y position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"new-TextInteractable","title":"new TextInteractable()","name":"new TextInteractable","owner":"TextInteractable","constructs":"TextInteractable","description":"Makes new text.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"new-TilemapInteractable","title":"new TilemapInteractable()","name":"new TilemapInteractable","owner":"TilemapInteractable","constructs":"TilemapInteractable","description":"Makes a new tilemap.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.get","title":"TilemapInteractable.get()","name":"get","owner":"TilemapInteractable","constructs":null,"description":"Gets a tile.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.set","title":"TilemapInteractable.set()","name":"set","owner":"TilemapInteractable","constructs":null,"description":"Sets a tile.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.getHoveredOverTile","title":"TilemapInteractable.getHoveredOverTile()","name":"getHoveredOverTile","owner":"TilemapInteractable","constructs":null,"description":"Gets the tile the mouse is over.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.getMouseOver","title":"TilemapInteractable.getMouseOver()","name":"getMouseOver","owner":"TilemapInteractable","constructs":null,"description":"Checks if the mouse is over it.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.getWidth","title":"TilemapInteractable.getWidth()","name":"getWidth","owner":"TilemapInteractable","constructs":null,"description":"Gets the width in pixels.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.getHeight","title":"TilemapInteractable.getHeight()","name":"getHeight","owner":"TilemapInteractable","constructs":null,"description":"Gets the height in pixels.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.screenToTile","title":"TilemapInteractable.screenToTile()","name":"screenToTile","owner":"TilemapInteractable","constructs":null,"description":"Turns a screen position into a tile position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"TilemapInteractable.tileToScreen","title":"TilemapInteractable.tileToScreen()","name":"tileToScreen","owner":"TilemapInteractable","constructs":null,"description":"Turns a tile position into a screen position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"new-RectangleGridInteractable","title":"new RectangleGridInteractable()","name":"new RectangleGridInteractable","owner":"RectangleGridInteractable","constructs":"RectangleGridInteractable","description":"Makes a new rectangle grid.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"RectangleGridInteractable.screenToTile","title":"RectangleGridInteractable.screenToTile()","name":"screenToTile","owner":"RectangleGridInteractable","constructs":null,"description":"Turns a screen position into a cell position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"RectangleGridInteractable.tileToScreen","title":"RectangleGridInteractable.tileToScreen()","name":"tileToScreen","owner":"RectangleGridInteractable","constructs":null,"description":"Turns a cell position into a screen position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"new-VectorGridInteractable","title":"new VectorGridInteractable()","name":"new VectorGridInteractable","owner":"VectorGridInteractable","constructs":"VectorGridInteractable","description":"Makes a new vector grid.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"VectorGridInteractable.getPoint","title":"VectorGridInteractable.getPoint()","name":"getPoint","owner":"VectorGridInteractable","constructs":null,"description":"Turns a grid position into a screen position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"VectorGridInteractable.screenToTile","title":"VectorGridInteractable.screenToTile()","name":"screenToTile","owner":"VectorGridInteractable","constructs":null,"description":"Turns a screen position into a grid position.","context":"UI Module"},
    {"page":"ui.html","kind":"method","id":"VectorGridInteractable.tileToScreen","title":"VectorGridInteractable.tileToScreen()","name":"tileToScreen","owner":"VectorGridInteractable","constructs":null,"description":"Turns a grid position into a screen position.","context":"UI Module"},
    {"page":"fx.html","kind":"page","id":"","title":"FX Module"},
    {"page":"fx.html","kind":"heading","id":"particlesystem","title":"ParticleSystem","context":"FX Module"},
    {"page":"fx.html","kind":"heading","id":"particles","title":"Particles","context":"FX Module"},
    {"page":"fx.html","kind":"heading","id":"particle-methods","title":"Particle Methods","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"new-ParticleSystem","title":"new ParticleSystem()","name":"new ParticleSystem","owner":"ParticleSystem","constructs":"ParticleSystem","description":"Makes a new particle system.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"ParticleSystem.addParticle","title":"ParticleSystem.addParticle()","name":"addParticle","owner":"ParticleSystem","constructs":null,"description":"Adds a particle.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"ParticleSystem.clear","title":"ParticleSystem.clear()","name":"clear","owner":"ParticleSystem","constructs":null,"description":"Removes every particle.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"ParticleSystem.count","title":"ParticleSystem.count()","name":"count","owner":"ParticleSystem","constructs":null,"description":"Gets the number of particles.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"ParticleSystem.isEmpty","title":"ParticleSystem.isEmpty()","name":"isEmpty","owner":"ParticleSystem","constructs":null,"description":"Checks if there are no particles.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"ParticleSystem.update","title":"ParticleSystem.update()","name":"update","owner":"ParticleSystem","constructs":null,"description":"Moves every particle.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"new-ChunkParticle","title":"new ChunkParticle()","name":"new ChunkParticle","owner":null,"constructs":"ChunkParticle","description":"Makes a square particle.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"new-LineParticle","title":"new LineParticle()","name":"new LineParticle","owner":null,"constructs":"LineParticle","description":"Makes a streak particle.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"new-AnimationParticle","title":"new AnimationParticle()","name":"new AnimationParticle","owner":null,"constructs":"AnimationParticle","description":"Makes an animated particle.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"Particle.getX","title":"Particle.getX()","name":"getX","owner":"Particle","constructs":null,"description":"Gets the x position.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"Particle.getY","title":"Particle.getY()","name":"getY","owner":"Particle","constructs":null,"description":"Gets the y position.","context":"FX Module"},
    {"page":"fx.html","kind":"method","id":"Particle.hasTag","title":"Particle.hasTag()","name":"hasTag","owner":"Particle","constructs":null,"description":"Checks if the particle has a tag.","context":"FX Module"},
    {"page":"threedee.html","kind":"page","id":"","title":"ThreeDee Module"},
    {"page":"threedee.html","kind":"heading","id":"threedeescene","title":"ThreeDeeScene","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"heading","id":"camera","title":"Camera","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"heading","id":"objects","title":"Objects","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"new-ThreeDeeScene","title":"new ThreeDeeScene()","name":"new ThreeDeeScene","owner":"ThreeDeeScene","constructs":"ThreeDeeScene","description":"Makes a new scene.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"ThreeDeeScene.addObject","title":"ThreeDeeScene.addObject()","name":"addObject","owner":"ThreeDeeScene","constructs":null,"description":"Adds an object to the scene.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"ThreeDeeScene.getCamera","title":"ThreeDeeScene.getCamera()","name":"getCamera","owner":"ThreeDeeScene","constructs":null,"description":"Gets the scene's camera.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"ThreeDeeScene.threeDeeToTwoDee","title":"ThreeDeeScene.threeDeeToTwoDee()","name":"threeDeeToTwoDee","owner":"ThreeDeeScene","constructs":null,"description":"Turns a 3D position into a screen position.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"ThreeDeeScene.threeDeeToTwoDeeVector3","title":"ThreeDeeScene.threeDeeToTwoDeeVector3()","name":"threeDeeToTwoDeeVector3","owner":"ThreeDeeScene","constructs":null,"description":"Turns a Vector3 into a screen position.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"new-Camera","title":"new Camera()","name":"new Camera","owner":"Camera","constructs":"Camera","description":"Makes a new camera.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"Camera.getX","title":"Camera.getX()","name":"getX","owner":"Camera","constructs":null,"description":"Gets the x position.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"Camera.getY","title":"Camera.getY()","name":"getY","owner":"Camera","constructs":null,"description":"Gets the y position.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"Camera.getZ","title":"Camera.getZ()","name":"getZ","owner":"Camera","constructs":null,"description":"Gets the z position.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"Camera.getFov","title":"Camera.getFov()","name":"getFov","owner":"Camera","constructs":null,"description":"Gets the fov.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"new-ThreeDeeRectangle","title":"new ThreeDeeRectangle()","name":"new ThreeDeeRectangle","owner":null,"constructs":"ThreeDeeRectangle","description":"Makes a rectangle facing the camera.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"new-ThreeDeeFloor","title":"new ThreeDeeFloor()","name":"new ThreeDeeFloor","owner":null,"constructs":"ThreeDeeFloor","description":"Makes a floor.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"new-ThreeDeeShape","title":"new ThreeDeeShape()","name":"new ThreeDeeShape","owner":null,"constructs":"ThreeDeeShape","description":"Makes a polygon.","context":"ThreeDee Module"},
    {"page":"threedee.html","kind":"method","id":"new-ThreeDeeImage","title":"new ThreeDeeImage()","name":"new ThreeDeeImage","owner":null,"constructs":"ThreeDeeImage","description":"Makes an image.","context":"ThreeDee Module"},
    {"page":"asset-manager.html","kind":"page","id":"","title":"Asset Manager"},
    {"page":"asset-manager.html","kind":"heading","id":"asset-manager-methods","title":"Asset Manager Methods","context":"Asset Manager"},
    {"page":"asset-manager.html","kind":"method","id":"loadFile","title":"loadFile()","name":"loadFile","owner":null,"constructs":null,"description":"Starts loading a text file.","context":"Asset Manager"},
    {"page":"asset-manager.html","kind":"method","id":"doneLoading","title":"doneLoading()","name":"doneLoading","owner":null,"constructs":null,"description":"Checks if every file has loaded.","context":"Asset Manager"},
    {"page":"asset-manager.html","kind":"method","id":"get","title":"get()","name":"get","owner":null,"constructs":null,"description":"Gets a loaded file.","context":"Asset Manager"},
    {"page":"basics.html","kind":"page","id":"","title":"Basics Module"},
    {"page":"basics.html","kind":"heading","id":"squarekickbox","title":"SquareKickbox","context":"Basics Module"},
    {"page":"basics.html","kind":"heading","id":"constructor","title":"Constructor","context":"Basics Module"},
    {"page":"basics.html","kind":"heading","id":"collision-methods","title":"Collision Methods","context":"Basics Module"},
    {"page":"basics.html","kind":"heading","id":"info-methods","title":"Info Methods","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"new-SquareKickbox","title":"new SquareKickbox()","name":"new SquareKickbox","owner":null,"constructs":"SquareKickbox","description":"Makes a new kickbox.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.colliding","title":"SquareKickbox.colliding()","name":"colliding","owner":"SquareKickbox","constructs":null,"description":"Checks if two kickboxes overlap.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getLeftX","title":"SquareKickbox.getLeftX()","name":"getLeftX","owner":"SquareKickbox","constructs":null,"description":"Gets the x of the left edge.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getRightX","title":"SquareKickbox.getRightX()","name":"getRightX","owner":"SquareKickbox","constructs":null,"description":"Gets the x of the right edge.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getTopY","title":"SquareKickbox.getTopY()","name":"getTopY","owner":"SquareKickbox","constructs":null,"description":"Gets the y of the top edge.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getBottomY","title":"SquareKickbox.getBottomY()","name":"getBottomY","owner":"SquareKickbox","constructs":null,"description":"Gets the y of the bottom edge.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getMiddleX","title":"SquareKickbox.getMiddleX()","name":"getMiddleX","owner":"SquareKickbox","constructs":null,"description":"Gets the x of the middle.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getMiddleY","title":"SquareKickbox.getMiddleY()","name":"getMiddleY","owner":"SquareKickbox","constructs":null,"description":"Gets the y of the middle.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getMiddleOffsetX","title":"SquareKickbox.getMiddleOffsetX()","name":"getMiddleOffsetX","owner":"SquareKickbox","constructs":null,"description":"Gets the x of the middle, from the position.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getMiddleOffsetY","title":"SquareKickbox.getMiddleOffsetY()","name":"getMiddleOffsetY","owner":"SquareKickbox","constructs":null,"description":"Gets the y of the middle, from the position.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getWidth","title":"SquareKickbox.getWidth()","name":"getWidth","owner":"SquareKickbox","constructs":null,"description":"Gets the width.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getHeight","title":"SquareKickbox.getHeight()","name":"getHeight","owner":"SquareKickbox","constructs":null,"description":"Gets the height.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getX","title":"SquareKickbox.getX()","name":"getX","owner":"SquareKickbox","constructs":null,"description":"Gets an x near the kickbox's edges.","context":"Basics Module"},
    {"page":"basics.html","kind":"method","id":"SquareKickbox.getY","title":"SquareKickbox.getY()","name":"getY","owner":"SquareKickbox","constructs":null,"description":"Gets a y near the kickbox's edges.","context":"Basics Module"},
    {"page":"example-platformer.html","kind":"page","id":"","title":"Platformer"},
    {"page":"example-platformer.html","kind":"heading","id":"the-code","title":"The Code","context":"Platformer"},
    {"page":"example-platformer.html","kind":"heading","id":"how-it-works","title":"How it Works","context":"Platformer"},
    {"page":"example-particles.html","kind":"page","id":"","title":"Particles"},
    {"page":"example-particles.html","kind":"heading","id":"the-code","title":"The Code","context":"Particles"},
    {"page":"example-particles.html","kind":"heading","id":"how-it-works","title":"How it Works","context":"Particles"},
    {"page":"example-title-screen.html","kind":"page","id":"","title":"Title Screen"},
    {"page":"example-title-screen.html","kind":"heading","id":"the-code","title":"The Code","context":"Title Screen"},
    {"page":"example-title-screen.html","kind":"heading","id":"how-it-works","title":"How it Works","context":"Title Screen"},
    {"page":"example-road.html","kind":"page","id":"","title":"Pseudo-3D Road"},
    {"page":"example-road.html","kind":"heading","id":"the-code","title":"The Code","context":"Pseudo-3D Road"},
    {"page":"example-road.html","kind":"heading","id":"how-it-works","title":"How it Works","context":"Pseudo-3D Road"},
];
